CREATE DATABASE IF NOT EXISTS filerun;
CREATE DATABASE IF NOT EXISTS piwigo;
CREATE DATABASE IF NOT EXISTS coppermine;
CREATE DATABASE IF NOT EXISTS hmailserver;
CREATE DATABASE IF NOT EXISTS lab_db;

GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
