[mysqld]
bind-address=localhost
skip-innodb
myisam-recover=FORCE,BACKUP
basedir=C:\Users\abhir\Desktop\PROGRAMMING\Terraform\hmailserver\extracted_hmail\MySQL
datadir=C:\Users\abhir\Desktop\PROGRAMMING\Terraform\hmailserver\extracted_hmail\MySQL\data
port=3307
